---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: romm
spec:
  components:
    - ../../../../components/dragonfly
    - ../../../../components/zeroscaler
    - ../../../../components/persistence
  path: ./kubernetes/apps/media/romm/app
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
    - name: cloudnative-pg-databases
      namespace: database
    - name: dragonfly-operator
      namespace: database
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: romm
      CAPACITY: 2Gi
  targetNamespace: media
