# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vmalertmanager
stringData:
    pushover_api_token: ENC[AES256_GCM,data:1TT4Dyu1oDbDjJHxu7qYdSL6OFSr7wCPoiWcCeCZ,iv:HIO/2Ok+YAP2NpJuJNM0uSQ1O2u1a/pfIXkoBykpAnI=,tag:/GxXaCJ6Mf1n3Kz07N+ecQ==,type:str]
    pushover_user_key: ENC[AES256_GCM,data:YPk6ghe0q4G/wedcqnaxm+NZ+1m3Pzt54k/7k1Mt,iv:5pcQslkH/eBokV+nJR4Aioo+8xXo3rsnCjb84jTFL98=,tag:6mKLdw4Qln7q8x+H0bfvOg==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTkhpaXYra3hMWWlIVkNP
            bmd6b2c2QUk4Vk0vcUpZeUx5bmxUb3laOVUwCmRVWkh3Tit5TGFEUlFIRStWR0or
            aTBwM1d4a1lDZm9OczBvZjZmWVcxTUEKLS0tIG43LzlGaTNidEt0bE1BM2hlelhX
            OTFSQmszM1YwOUwxUERJdzNZLzRoMEUKxQK568H8T3gMF+yqZMgMfzniNcDQVICM
            knMQPsnOtIOk7Ch/2msiCKW0fiWjmPbaeu2KWJWtQqPsoyDI9mGpFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T08:50:06Z"
    mac: ENC[AES256_GCM,data:dbXWrhZqK+xUfJAXToyE2t19GpTmeU4t1fjiDPJU2GnASvA2DS2NW1kmKHgBfa/C/+hNA1re4R13mVZLtX4kwEjkCc72D0lU+3LuCxYq+Oat96ZrSe20+8tlrwnHzKCRfVl/sIkuaRkNeaBJURYOlbtoBLBpH2KGYp1jEbzzI8g=,iv:tge1gBXY6Loespsf/HRStg6CEWeZYKgP6UpR9CYIFk8=,tag:DBh3qqp2fsVzGb7+AClyEQ==,type:str]
    pgp:
        - created_at: "2026-05-02T08:50:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAf5xyd0flTsZzmEy7XLfwG1yWdywP9tGub5v3iYiJbHkw
            18u+/KD1zjbdiaBfhAQldkknav1FHOVmNK2EkE+4U09/FkRBXo+T983GU5jMDBP6
            0l4BssBFDhkFyQbPficIfkw/dL8nc47SezMn4KO342ovM+gzEifjfKCvclZFgEMP
            AuuEyLB2sn1JnYP/RMgl9elCk3sl7PqRumSKyfDVHPobTb1RAZHQ8hBVsYIXjzdO
            =XXv+
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
