# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager
stringData:
    ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:F1VapVZywcWNaC4dG8fVOjq+mRTmaYpucHjBa1aU,iv:fZGSDnUBk8GaKukZh+hMx1xNQgARjDO2ufiqY1VWBGk=,tag:amAM7gmBd574cvVIHPClhQ==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:QHdnp+xxBVFdbTFHT/hlPZv/GZDv2+IrPguvZv2C,iv:/GD9ov8lEjUrpc1fhCIKEuAWSDkjzpGQDyLt96VuN6Q=,tag:5wAlSOqFIn6bI1EGc+p9LA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTkhpaXYra3hMWWlIVkNP
            bmd6b2c2QUk4Vk0vcUpZeUx5bmxUb3laOVUwCmRVWkh3Tit5TGFEUlFIRStWR0or
            aTBwM1d4a1lDZm9OczBvZjZmWVcxTUEKLS0tIG43LzlGaTNidEt0bE1BM2hlelhX
            OTFSQmszM1YwOUwxUERJdzNZLzRoMEUKxQK568H8T3gMF+yqZMgMfzniNcDQVICM
            knMQPsnOtIOk7Ch/2msiCKW0fiWjmPbaeu2KWJWtQqPsoyDI9mGpFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T17:26:35Z"
    mac: ENC[AES256_GCM,data:Pm2NezrmAkdCNaqtVM9Imhf+BvG6U+rygJxym8PeVfWoqkCw7zfP1wejoz1QNG8G+FzdIdPJRqHpq+LV5nivEHCm2mgckYXxBfNlc2zMztvitVF7GHnE9KQWFDZf1db6UHgSIL4hdatlimtuJG9HEK01kodCgnhUriTn5xHEI+0=,iv:KRUH2Dn2kxiSVPuRzOyEmLUqFqWM747V5hnFyimzAIc=,tag:XIyO0n4LbSFPXx6thhOhvw==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-05-02T08:50:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAf5xyd0flTsZzmEy7XLfwG1yWdywP9tGub5v3iYiJbHkw
            18u+/KD1zjbdiaBfhAQldkknav1FHOVmNK2EkE+4U09/FkRBXo+T983GU5jMDBP6
            0l4BssBFDhkFyQbPficIfkw/dL8nc47SezMn4KO342ovM+gzEifjfKCvclZFgEMP
            AuuEyLB2sn1JnYP/RMgl9elCk3sl7PqRumSKyfDVHPobTb1RAZHQ8hBVsYIXjzdO
            =XXv+
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.1
