[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
JUST_UNSTABLE = "1"
KUBECONFIG = "{{config_root}}/kubeconfig"
LEFTHOOK_OUTPUT = "false"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"

[tools]
python = "3.14.4"
uv = "latest"
"aqua:evilmartians/lefthook" = "latest"
"aqua:FiloSottile/age" = "latest"
"aqua:budimanjojo/talhelper" = "3.1.7"
"aqua:charmbracelet/gum" = "latest"
"aqua:cilium/cilium-cli" = "0.19.2"
"aqua:cloudflare/cloudflared" = "2026.3.0"
"aqua:fluxcd/flux2" = "2.8.6"
"aqua:getsops/sops" = "latest"
"aqua:google/yamlfmt" = "latest"
"aqua:helm/helm" = "latest"
"aqua:helmfile/helmfile" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:kubernetes-sigs/kustomize" = "latest"
"aqua:kubernetes/kubectl" = "1.35.1"
"aqua:mikefarah/yq" = "latest"
"aqua:siderolabs/talos" = "1.12.6"
"aqua:yannh/kubeconform" = "0.7.0"
"pipx:makejinja" = "latest"
