---
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: containerd
content: |
  [plugins."io.containerd.cri.v1.images"]
    discard_unpacked_layers = false
  [plugins."io.containerd.cri.v1.runtime"]
    cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
    device_ownership_from_security_context = true
---
apiVersion: v1alpha1
kind: EtcFileConfig
name: nfsmount.conf
mode: 0o644
contents: |-
  [ NFSMount_Global_Options ]
  nfsvers=4.0
  hard=True
  nconnect=8
  noatime=True
  rsize=1048576
  wsize=1048576
