# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: searxng
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:O7teAx2+cAyKyqR6jXKSYmhuGCiaD9UeiY/5zAelf4cpj1+4NNYWrooVcBolRpOakpyrVjyyDCx71LmmlkktuQ==,iv:ZypJ2OlVQc988ta7O8mcvWI+SaUBCzROLKaxRygY1nc=,tag:kFmWh4MCLJaetUYoqAJ10Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY0xVVTFGbTZLVTUza291
            eWE3QVRmNFBENERSblZQNWFMeGIvNVV4YnhBClozUjBscUxNd3ZuQkdHM0xDclo3
            aWthUnhmS214bG9GQTBQRWkxWnl1dGsKLS0tIFNyb3VRTTFYaXFMclRDMGNHL3A4
            cU51bm55M1gwTkg1eEMyZTBpbEpveVkKinZhmcab4n4UI4VJHAzVQyt/B6ABH4KZ
            U1o0Ni23I+1wBw42e4JA2TaCVcsCWfS0MxTW5iBA3aVG+CcAfa4Dug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T07:21:06Z"
    mac: ENC[AES256_GCM,data:cTQv4+6WMN8amUPnzzhmSu6PjwFuRffUVWYfNlIJ8dM5dAciIJm3n4uv+L0ij7+YIIkeg1T9rLf/Qw2IEsul22ve4wi0YxAo/cQWsuog46PSEQ2npyEgTrPEihLJjVdfRzhu4zZTugccTY/8g5ICRJTNnmP08s+dlCA5E+RTp6g=,iv:7v5U7rDnPOzenLMHgXnn3uNXvonWgenZpV13kGIVXug=,tag:wwKQmsoZiq9AT+ARCtHI2A==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-05T07:14:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAUEkF/Tz66XYY6CbviSgzRCroavoKkS+GzFKEGhYitB8w
            xl0t2m4h1OWtGtpQEdwhaGE+Lge5SxjLYndK9lHXkBPHTRF9qzcBEtMOek8604uG
            0l4Br8t4i/kgXLh39b577o3Fz7bQMycMh3gjTnQ8OP1rUpr7RBBxRpNn3ATBMaOw
            lErDDESWRCTdtxM1uMkrui296f7n54UR/PoZna7y28mC9lcB761pS51TNnJ6bQj/
            =W/60
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
