---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}
spec:
  accessModes:
    - ${ACCESSMODES:=ReadWriteOnce}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: ${APP}
  resources:
    requests:
      storage: ${CAPACITY:=5Gi}
  storageClassName: ${STORAGECLASS:=ceph-block}
