# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: context7-mcp
stringData:
    CONTEXT7_API_KEY: ENC[AES256_GCM,data:M8sshXBql3wjkTqP52wfaWog7CnyE1SG+xCidpcjjkV5OVUsnn/Blzf38Q==,iv:8IUABwfImEnFVEzquL7FCWSknRxot3l/h/G/gtLai94=,tag:GtpteO6rZe4V2iZkAAH2pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTE1NQkFhcVhyNzdxOUhl
            SnNPMC93TUtRNjEwUVAvQ2o4VUpwOG5aZkM4CmFzS1BtakNLUktyclN3S1Z6N2pR
            RnRiUCtjSTZoUldSNUI4RGFPMVV3Y1UKLS0tIEszYW9NdWRYdGgrbGVEYldGQlds
            a3o2U2s4NmcxMjArQmptaXNTck5UTWMKHkkNcgdpejTKmGn6FTsnUGIgB2X5rX2R
            ro1nffRarSBqr8aHRjyPy0C3mgm9qJa52C4qQUyMlyDJGr8oIIpgJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T08:25:50Z"
    mac: ENC[AES256_GCM,data:25LKEA47S8edo5OqPVFbmwAV8IuuZHCrmd83W8mfN8xmuf0uUxNRv5K/xuk4ZG8c7iSqbFSYHdSaUAyqw3XTqZYc0eRwJe0+dc1rdR6bfHGGnJvQ+hs1KrWVGuuIm/78yDSLNVV2uFtlGB6jvnacdgZmyRlwtZU7bMOa7jgQq54=,iv:hk9RmnFqy3xkJtd6yqT7ganMjHbIU/HvAZ4QN6VMxX8=,tag:bavrKTNNpqEzlmr1J4Nh/A==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-15T08:25:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAUrTllfYzSCHmrZzDq8mJiKEgYl9toD5hPlR0Tm4k9Agw
            /AklIf2LvnmOqw4VrnNjAwH6S2d2aOzjmmWcnZ8NKpOJ4mOM/eSaWQpp0wtiS9ky
            0l4B/NGHW9ySxv/CTvPM97JHJe0DBO6YQLuZZHMezw60SE7BzxZMZi8UebevXaHO
            ZJi8ngH1yyUpcy0M/UvObyEeHeXJJD4wIp52HXD0Flp72JWaFJNvznHrqbAkW5Bh
            =PGMd
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
