# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: konflate
stringData:
    KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:gfOwr5ILk/fpMq91BDqpdy+1g87aT0azeqWmB0sELc4VwCJR3T+8DHMbWH+8PSwXFMBlKqh/p3VkDM/B8CV1Tg==,iv:5lv3U052DoftrkrI/Mix0ZImnkl1CqvOIeORhx7hrK0=,tag:/dNNtX6vo9MzMgkgEBL5gg==,type:str]
    KONFLATE_APP_CLIENT_ID: ENC[AES256_GCM,data:wST3NYhSzzc4UxEjp1NN2/+iKRI=,iv:OSuAKaEbS9CBWmwGAghf3MAi7awC+ndTXDDvODd3n9s=,tag:xFF3F6zgitg0kmy/XuGqww==,type:str]
    KONFLATE_APP_PRIVATE_KEY: ENC[AES256_GCM,data:uwVSL7+nkhKfqaeZN6iFdZbjA/rjaZIasDgnbhM/6akLkaIJm4SFcdRjJRgqd+s1EeZKrHDZEbrQBViy1z5+tAH20ro3JxvvUzF46aKkxPZYNaRlJYEIsEF7V/m6a4xwbbdDDN8fHyuL+g7Suqikjaf+uXiPBpE9GE0WMzZiMmzdtcYl3z0EEgljpHw1cb6ZFYkatoYWjpXfY98c5uUOZo82XXPmsE/v1nG6xrX7igGfolGEUpcky2v9+cHPCSOzrWcutvUtTjZFSj6VTUdkX5Sk16yPecsOzLlmVaGrsR1yZfjcTt4P95x6Y+eeAgKai6xdHQHdanAyZNNtMlpM5jRXxNyrpNG1aN5nXr3NVCqRlxUfeS/y2t+7BlsZwdDE0oeisEBA5PSNU2BXw5BxxLRFzC5rlH61J1jMzQC7wM+m+V5q69gyBbIsIDGF3hM2k7zpN3uKwyaYI6LlhYdhGOawWmqKO17DlRO52EgWwYPH0jNMGYOm2EAtUU/DWQ24HrTOm0+SP2/KxR0JdVk4bVavurFDeGZp3w5/qjdgR9ui3IBTAjrVkGkvjO/Gpww3+CplvFQHy5mLN+Xd+aspjH/maoZaujIj3Qgk36bqBSozAoiFeO2Rf7bVVsIxNohJHGbNbWogmmA+/XGVec+1pHRH9f/e177UkX0gvtpK4UYxc9mbT6iNh9IOVqzRHZQiBnr6doAdu7zAaDXbb+VEfxDOrjp0A9o9ENiXlYIUZE9SAb/yS/HUBtH1kq3hBAOidc8mwHv/9a4Dx8MyuIhW1QB7CFEI3UB8ntz00MHZFQw12ZAe6pvJABVIYSjcGZ8rXuXI2RFBcibZY99rO475F2dOwedZIJn/+Sq4hHNoUp1ay6+Gfb/Qtdb9xwQXZwXWyrBMpXxl3OnvX0XX82rFfMc2ZRFXUCIdOJnxmX7c4XHgcUhQQXOZiaO+lLrTYupU5s2FkRnpUTdj5cE3xK9RQWHcQwG3EzJ0lBEdlh5uzoZzW4h4BZOcntd28d0QIPtsQjcdOAqzpe+RQuzaVwZdX/999la6kpV51J75WFgGTUQo3jx4EKZp5G5F77Vs7ngeWJEyroFvlYOGzPRtZae/5eLFTgxltmPvMnGzRPI9G6s07xVJETI5/hVON+Em5KearQoakxFHISXmIVnetwkf0ZjLOrUVwO4NZxoYhuytv/5MAUgGPT9isrrlTorsiBRpx0OnDV41FJutVY10zfge6QpuFJnbNWc6/+ipQeU/o+KwQ+qobcM0rvo4MsB+4G5jSlkv3dAGJdOrykL5qyO+Szfqsd58Lnn9eG5VGjLmiV4lVkQn0d7mdX3Mr2mjkkbktdV7jG614pKWeVSPGG/ONYsylE5SYAiH0ns1toIJpIacJKbAUlICCoKLMrUdImoFJ4Z6xtwHbKlvkHMr9C+a313sLmkUkHrZhiKsRYgkStSTo5A5MHt3JQMcjUPCco2pAKINHWzGrUPZEK+f0EbJW8MlD14H++awZpDUThOApBIW7d6OBQBBYi3IyXYrF348v6XDS2K7QSRaz9ZKsuvcgYQJo/7W9/UTHXI7QsHO3a2H0X33yFER8IIoS3nmy/FtSWwAZEOOS2nY76E6AeH8WGKUTbq5A0KINMKahkBv/bVnxnf8KKifTGKdQvnJ77mJKl4W7KhDDe86l+8MIaxRHLnEMAUiH+ZhtMOm9dMy+Tpjnh0PayDPuMWpO9sN48KMJ9pqAja0oPIb+1zRqGCnr01Id5rw7gSFEst5YuhgdjisnwAT4fZGTmdHmk5dVSdAfIj4ryQaMvGz3ldGt4NaYaFwIvHg+DuSR//ABcCT/AfNZxHQMInieDQdNdk5uQQL0U8HJFfqNd7/ArNOlCPxnlIUomoD5S5svlGaDLDB7VyiWQCdh674ABhjF0CUi3ga3YeMlqibaVwLMEA644smLC/BMJI0DjWS6/GTNu7X/b7QAtSysi+YhtbtweLIq8pjl9B0z8w97mGvOwCBWJWzGXpUHR0HXwOprWbpujfC4eeLr5UWJV6VPObStDv/0zqwpErVlqW/RflgsW/dfehvWLZyq8CrxsGdamPLa5mdSJM+IGmvZU8wyvtci2yn+lDWoH03FEuwRFz5gKYfCb3jwDWmQ4GQIjco8ib7W4Tltf8mEa0tPBXWiwY2msozdo9KxDF+9p8HUGO76lafVxVfgQfnY9tRjw1FnEbXW2zepBmST08iky5Snvt5mLERNw==,iv:kaAQ/x28c/N3yl6H91/5unfREydlywDdCWzMYxfI4XA=,tag:cLNp4bmb97AJFHN7xgIMgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhUnM1bEJNdHhCb0Jyd1dk
            Zjhzc1RLQVQ3cm9ncjcwZzBSZjBTQXZxazFvCk9TZUN3UUFxb1Bkd2RyZEtzbTZ4
            dHJELys1cnFuOXU1T21xRHFrQUFnbEUKLS0tIDdjV05ORWZjVGlVV0NnNlVVMWZq
            dUFuOXNTTHRjNEhQTndzQnFBN1gxT3cK5wZmb87afcUBeF58FXM9J1jCLnPRa5WX
            7Bjxbl39OlvQON0gL48HJxTQHyKwJpmHG8ICpuf7MNEcGhhMYC9LdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T17:50:12Z"
    mac: ENC[AES256_GCM,data:cToAlIIJUnqbpNAFN/wgfoqx97jUJZPBONVdDOHhutpVDfHOH52w7Bj0vE1jgVWO+vFdK7lxrq7Hf0Yho1X8wIHBC/0s3VKtaJf8y3Y31jYcXQwRNq9XOYE0grKbER0RrgQmktoTtl2k9kejeFam2JulDCT8grAiffQmETJT4s0=,iv:hqOdpIdpE6Pe917WLXCNheEHevd68wt1rSL/ALHKo2M=,tag:8NfjKZ9AnzMUgrKkcusRKg==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-06-27T17:49:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdA924gq604YiQUZ1zAwl9eQhrmIrPABlMOmpJjcpWqFQ0w
            RdNqZ2su232HYs6S8Q5pF96FMtmunJ69fvD5x3vIsZtHyx6pIA8hk8cFJNs22skR
            0l4B7Nhftsm6WKT2T7QosUpwAtEWEo6g0zt9uQMe3iciHaOgm9Vdxia2iOn9ZW9n
            E9rPOIYwefqoEnNsymC9X+SfDy/7BOxLz8RYtq+DsJ6ekA0M4NaqiNegsjkAmNeq
            =zZLq
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.1
