# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: litellm
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:ZHpZhTawst7pjC2693x0jJ9xMf/PqQ2j8TzkpHA/zCOV8TcMjkMZZrcCANcjNsEYV0tG+BD8gkrptsDzVibEPizdXg==,iv:Lb6Oi4e8GzSuqw8/61lJEAlkOaEGhix8n/j/K6Eox34=,tag:mE2gzz4RM/Zse5YwkTGLUQ==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:gYjG47kT7KzwrLmZEF3rk7AW3XrqGZPLLJxJqp3UxrYP80QAJtdTIMYrHDJOngauOPEOTM5GUF/3j0/1pQMib+hOtizwKA9/G1dsbTEPNWGe2j+X27rA4c7E3+EpgkD+MCx2dYSXDKrP7KKL,iv:7BQ3h8SYaDaYXnA2a1nUIAA+MSlluQFOOoHUAlkXck0=,tag:ldoVjqHW+yCIWSI39lylZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZlBHNCs5WFY4b1BOa3Nj
            bFRvM1RGdzR4SW4zTW5xU1lFcVNNUTBGQ3lvCjFmejJFWUcyNHRDdEw4a3VHMGw3
            ajBsbWJRTXhCc2pseW9QSVVGbW5TTE0KLS0tIEdySEdUMy9MNmxtMmEzNE1ZNUs4
            M3N5TkFpdUE3amRCUXovZEhVRFdKZWcKWfxMu917QDkoO3wcTY/h10BfMXIhxqCK
            P8JaO6uMI3GYSFzXlB70mX1uGiOk6Htf50W5oZ+uPu3sDhgGloDaew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T06:44:08Z"
    mac: ENC[AES256_GCM,data:dv3vxIOOiTvbNmh3ZF/1do3QOnIqcBP0q1dpKuRs+LUg8R1iOe2t8Ahtg2wdNgHKwqieTR4TdtFX6AYB8zjOpycZHQMveeqLGROmG7SXB08sU2NzU3lr51cOGPRa4hRYAo0nZvzYbisapT+03qH1LWAk35mwv8g20RBFQB0YrMI=,iv:TK11RwgKCvCPI3XzQDo1ul/Yoa5UB34DEeC7bQhh98o=,tag:1Fj6TkFThbKXuDMsDO+cow==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-03T06:55:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAKERoH116OJS0uL1FY2TvUpCNF398+0p6jHrUjPisYHow
            lJzb1IhJG1dwHCKgpR3+jg30RtVqo4n8BP9yHytwTy28upW9MnrPjfYvR/FnjZiK
            0lEBnVJiVfn+7qc1a2DqlOmE9fuH5X+JPZ705ThVFnwn/vi49w26IqVII8DKetvW
            /Ujw6e09/ewZLCKHOfhnb4QzPuDGke6A2odsD/fmFlnArjI=
            =r9PA
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
