---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: open-webui
  path: ./kubernetes/apps/ai/open-webui/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  components:
    - ../../../../components/persistence
    - ../../../../components/dragonfly
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  dependsOn:
    - name: litellm
      namespace: ai
    - name: dragonfly-operator
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  prune: true
  wait: false
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: open-webui
      CAPACITY: 5Gi
  targetNamespace: ai
