# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: home-ops-runner-secret
stringData:
    github_app_id: ENC[AES256_GCM,data:NG+beitYNw==,iv:hVyU8efFVM4tVYOOkuw3SFGLPRYrnNPqcGBPptBixH0=,tag:9l/Oom8U1zNifWLKlusxQA==,type:str]
    github_app_installation_id: ENC[AES256_GCM,data:GC7ERujwzy4=,iv:JEKKO03qI9JDfECjuNLsr6sQ2B1fQ8QyURxUmck0bWA=,tag:4AfKdX5xy05saIXNPgmcpA==,type:str]
    github_app_private_key: ENC[AES256_GCM,data:wRpVun4r3yEVkSq7GWOrhqomQvE+JkALaHWXCGUjTwBxOvhBmaiIC49jAFvST/RGOfOrBo/8tQoVt6/IjIJ61e7qu/7jkREq/lW1xLSBq/vbfnwu2vaLAoKR08i/24kQVO+LUf76OvYAZA4u4ziPcj4SMuTg++sX8i/LhGADb9u8YyfqPkPCwtjAOgmnyeCc9l3PlDdy6ODtgbEw4eVLIkA0aylHGEJHF/WGvpIzGV/IaJJEw/ullkgIdzApsotr5zEKJP84dckBBUygmERU4HvgsIY/lE0u3QV2niQGhZogC6Id5Ub0kLJKi5kSsBpgWZW1WdvWbbGnPM8M/s8LlsCw2co5NxBL14DvnFOc2iZ1GAzJxa77Ig01pof0frkgGr6qXMwHsoGZbIPWJazvwGWZqH7iE3TIZep6T6eMFXfpK9nTh7iTpTHzROcWG3Tva30LhLneB2D2wul3sL3Pas6SEwMTjMaBJFpRqFXKYapgluKGAEkU4nxqvre3VCoFcuQfSWvA/9HE4AQftNrmtdourtfeN8NLiqBLQdyBJ9LXPllaMPLFH3RcvJWWgYPEqH9wOHyQtu2L7ojDpTNi+TYjQIwYa4i6hICzSWOmqOP21Fn1p+jsrSQ0ZDdWgwJLHpkfZwDiKOrpm/zXo11kUgUzlyFOx47RBNXshrVxJFyPjxVQHkXZfQx3bf4A1XFyWtTnVoz++PgYYEY3Dz+ebmxnv/bVfxODC1EqRoC3Bs5OkekAV87cwIkZrtPonvTSOfu/TCb7MK0YUuiP/Qsu8pD3fTMy7SqFJe4E6ENzfBhI6ifuXfSlcmt46Ywb/OdHkJBhQOgA3WqwJV74AqXHu/JFkyZfOrx7ngsrygS6R3WrB+e8JPSC8B+wy2lvSGqDlOVeBWpaZNjjTNBrD//10Z7amO3T9uxWCfrPSQ0KbV1AQIIMVBzQCJkk6tn38G+pIHIOnHXCIzjF2DXWdw7DmVVQ9NB5B4WRvoYcc1a50mEoiFAby7qJTSeaI5H7wU21uGh/YZVHXRP2x2SNUFf7mC9ZOqeBac2wRXxSBVMjJQIB8VYyZVOUjHDByFNB6TjfmJgmLbNpPAlBt53iATOwjU9AosCkc8/Sbrgaj3l3E35xVyUCFUUhdpTyfrzmhdyC0yYvpsai9EgB6ZBwbLJY8f93RBpK4cY4Rajw0n50m+OdOcA69ME88elOBUX+hkg4nIOjPCXqQkfkBN2xxSJpA0vPCi5gI4r0bED6TVQtPwpx2FwjdXIRPC3j/1fow9zwGqU6Kd08LXstLDHPDwQKntUZyTmrN/eycpYJBNnD7tyHDtPpAzJIAyMmDeHkNsFcdtlX2cEg3bNTli7VI5vmSKGLYEwMQuTYAQxy7g/iS3TzokqDqADQkXdR0VaFa+BsKL5151Z2ugMfo0CmQZPpxQrDxJms8UHFiZ9rsMiQ8hD0D2v3u4+entQHneo5M9zSXt9uSD+AQ6Y7acbRKhicqPQ/mzt72xNxqFQ5vXtGdCI0LLjhbmZiltUQDWMHtXnTt0XtIvvlzPGEqbBkAH/YGqTvLpdeN0RAuRw215yD1/Y1FDMw7t2qAgd+HVXrUsHACYS8bec4vKGYq+zM05PlhFol7itYIySO3d3hLxxiud4GuK0ShQ8kTJ7PwrIeHpY76ZEJFsKukr0BYtjNR3mTgJ4ISq8L1FUJeLaQfGSVEbFH1xiJqK5BOuHibGqSlfCaBc0FGmjXGTBhcsxFiNS7p4rsHOjftO+73KBBy5s28RcznWdrcPWc60+q3B1JYioqBB8Dgv3XmXFrLzzOxBThLZ11YKHqb+P9d13F8/v4BNnDGJy7nPHfhQ9kCQ+m/mY07ZzgBQtqz0eiwificb7D1W9WATea1yU28ol/3RZmvzqX7YDOSVmkAzOQIXiosZLUvFNNluh2nrllj7m0OuibCk16rzj6YkiR8tpf06HM3rOGyhyc/jGNAchWLmmscnW5n/8Qy0dVrmQpwEsnVoma+f7vZ5UmUbKaqoO45rbE//+D/ce5qIO9mtGTonj7uoPmSCvFZCjV6snrXfurjyGVHSjWChlgdE59CctecERka/C/UNR/hkSq5AK8ljLfMatM10pxExZipSoMBf3LhquJJ3BV5c3MYf3ONS5DA1Rnc4LYDk3IwqHH/T3yXPhMSLhULHQvjXt1WyQhzXeIi2qajNNZYSaX0AEdIeA3XKro9pUlAoobBk8xscOt2MXEnw==,iv:nRNXoPr9+EN5+y7OfbT/dWyn7gHD3XCmqAumm1zh0q0=,tag:q9+KNMzs+wTkJYQTug9GJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSkdXT1VsVUdNanBaNFRL
            YWRkN0thaVUxczhUUjJzK3E5YkhGUDM4ZkMwCldTZW5JeUlRK0tCRVdPR2IvMHpX
            Q0hOcWJaM1h5NXRZdGFPeFdETEZWZDgKLS0tIHRyNUowTUtlSncrNmVZaWxkRW5L
            S3ordGJzWStDYWpBTC9kMlgwME9WeXcK9wO31lnQE8jtYo8+fdIR309310OP3Gaf
            YBpMjihX5leDjBQsYVvLdUaW6a05oirVkpHrMYKa/LUj8poZo4tVZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T16:01:57Z"
    mac: ENC[AES256_GCM,data:Cgg3Jn54bFuApkn/68dV2PdDNkC5wB82d5QRq2O9jREiLVqty1Kfnb5nekbVsPK1l4YFMzVUacqE8LdVxf+iXoBHmMdqrMevrW6xn9twvJ4yWVgRaDf6HbcgOX8O1aanA+/SGHrjOzpuZ8snfI4UDMDrq9wFVL1IYX6iWofGBLs=,iv:7Np46d/UgcA6dgEVezz8JKheAEMmNcrC/oKp/+wz9qs=,tag:5l2sbOUPcOkM+hBbeCbGdg==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-06-28T15:57:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAJd66S6NhYvcKU4XTZvHMiDqHpEaU6AwaXTYG/wRUL2sw
            6//aV1fUPNzywpsV8U3nANVqI/wzWD2in0MeZOYjpTZQgoR+iUggW1DKqXIhEsRy
            0lwBBgYxP1Ar7lOz9pJjbIkU0BsfHYwrOgc/5FzddyVtXG9butlXJVFHeb1Qloio
            x4EczphtdmQTZGlQ/lVhTjZEaEDq0ZnWV+3FeMJNZ4U50Bgcn3X3BH5zPhTApg==
            =83+z
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.1
