# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: home-ops-runner
stringData:
    talosconfig: ENC[AES256_GCM,data:QrGty48gyhsq1lDAnayWXR5llcJ40bW165lJJTMsKmu0VT2ignFeyko1GuH5oUfsV4YCjeMUYHjP1VCMDpkeRkPqPzU7tr8+byP3vndzbG7cFr2acMeSpuZi0EDi7Y0MHWOldzt2O7c01/uX/fOTn1W0FnYbk+q0k8tP6wh5FO36/9VX/lscDlFnVthYw6QHz0h6z0flQ+eUFdTfu/2lpT8xmZ3bxcSRQjzI63z9LxIVpuSx2MZRJ0V/Z6K7qyNQVCX2fvIBth/jFhDkPNPtOiCb9LJqPZUgsdOMy//diF5wqhRX+Q79glEeYsY8UlCZq49FxDPG6Z8Et02ywBg9K3PSYyIfYVbxXWnal+YV4uS3e51QUhg065U8xASbZOdtI0DaMGsjUqSCbCJSQhqLuDiIfyfg3/eaqywakvmyuoORLbqOyVWCvJvIo+VK3r5ndDQbb55k9bEE0NBZQ8EfGOAcxDfsI1uA9MIOCJfQMYE/TgZsLr5FxVFzRKey2Zn7oS+LxjfGGz84IIImcVVb3GpRxwNHk6hz0O4xe4IKJKlu4B5ToGWCjOnfGdQx3LZenweh6tVrsyOHE6oZOaSVfXdWbx+XhjwFzcgWIa6CTBjvbd0/qJd8Ev694BocpwZYgZVeJk3niJOLwGvz3/fTp177+3cRA3u/kF45cc8XKiuH/A5Q6Cv6zaOBO6gdPi4DE5Ze8p/58H8cW6VOlJ3Gm1pu9iLKaHgFSc630qqIfm+az9Mft4dhpzW68lT2CQ761InJL9bOXzd/NWpiXsmmMSVnT9AUh0H8j1w1sSK/yIkmoIP1q18tf1t8jxY5wc0Sk40xv0s0cEdy/ijGVN/W9bkXDmxK7BXTLmEX/k4bC4NHnfoTzztNDCe+ginF96rszrI89aaWhO22BG/avUl+oo7XIg/A+EVwYA4y/W46/rzEqoctR9hunPpEWedn748D2E+I3FMEsukCCaJVzELeTuoHhW0AHK0JDx6MB9OEjIDnVqLeV3FgU1XTvf1Pm1l/Kb3QwnCOENqroIdJ0wzG6BNiPqZWVgOCcBkFRh3m8aiPe1naBrFxsj9C8oAwN0wXzlJUmrCdJeaQvxVW3o8qTacflN6BUn3MUV4/3UNua0CxvgGnDffc9uyVfE9/nL8yEhJax/NAz3W0OC/52ZUyEI4EIAMJskz8W4TznGt8bOSHvTrJmFsqSeRpWcYV0kCr0S4/cLyg2sTKVbH9d1P04X6zqw3/pWbTp2QOX9OP4voJ19VNoUx1tvBCfJYRUAC/UuHhT3dwTlycJtvAd75oH6xnaOXk5OTMbd9NFUzS8sKVQc/jqET60H0X7f7EOsxopC9b38dWcoA1XMQznGh1dPi4uAlMFj/izk/YaJubJqDTgeVgSbS6B3PKNYIEID9BNxYjLKFQjjkzk9pUjmjGGssxWH3h/kTd6fMN96Vn0//mheIJxobTBG7rnu25udgWqVPc18ZEvFRqvccx7U8t9d+A/mImx09lLZu8Q/kHBUEnDMeyXazQWVZLPOLeufAer0kkv/I0G14ber0Hm2fwYnh6eeOuYNH4adyv28vRvbuYFls0bxzwpbqSn3xIh/Vc8PYbQzc+Rv55L37/skEjRj5lANlzEkjxNFvGriVdavJoFZoJs5ijOqL6ky+JOc9Amk1uFXaTIRRLNaU3brrl3Vv+4kSGJLqfw2bhByKHny5fcl1UWu9ktTk/LKU0Ki9CyEFaXww9B4DHfn9tbUFORQp8QaQkjy1SYSceU4mY7WdEGOY40zWqFxxT9Xnqxy7SUqH9cr1Oeoe2Iyrla9v8Tusk4umFaFXVmky8NH0zzdRvmJSj494Fz2NRezCHpDP7IF8xWEkkFInafTzoEYPUoW/jtqygh+Q9rRGk32kOCs0mY8wvjEqmu9dBFKtVBTPX/5hSUc0QnvusHJau1sn1IYTb7S3LxLJYk06KxrDISqItFdnv0sOJHIRAtJRaqHDX97RCwTuViP57Nhl0Z6BW9nfKa974R7nN1j9ErX8kBFDeVFpC2pDiUoltUlLzdIBsdaQraZOs/aoRgiR/ApZ30fRuoiNdvetod88dEnozcuw+BP0H4GOO8JOTbdg/Y220atj5d/VKq00TE6Jr36IVdJejOXC72Jjo30KF987TzhyZ+bKrnUKKmXKI/FuMo7Rm8W+o5RI=,iv:z4rbcodZJRw47P3Y6IgRMT6rgkHxeIVRW314jpnsj7I=,tag:2fZKgoqJ/ZcLPKaH/JMFRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT2paYTMyd2tVVmRYcXhP
            V1BkbmNRSGtWK3lFUFVQQU90NzBIQnIwdlhFCi81NGQvbGlxamNiS3pHUzlLdGRu
            aUR2QS9qeGw1SWxJV0VJa0NpVHl3OTgKLS0tIHpqcVJXQmtyUVpYSG1XYjFHTkRL
            NDhtREhWSVNNYkthOGQxa2VMV0JjR2sKRAf0gyqfGDqKbbWL2blOxWKlU1nEcHiJ
            +uylnUDS6TilYG0jkXnGagx4DlCTjlwortX4RZ65cuI2CxuK2IgeAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T16:01:32Z"
    mac: ENC[AES256_GCM,data:aA095pwHYmmSX+ufJdDfJFomcbtUP2tGLZQjCZIVegFQrcMas46x25U3owuleIZ9UHIEcc88pXTiNYCTYTq5FmXIqbra2wF3bbDRpZotqmPT+/EDWgW7k7c8vXWzNbuqgpqTJqINhaIhcseKwUQN9+w/6nQR4pfMGHQDOv6dhzk=,iv:pxnWSwUJJiyKeNz0D5okqA9kkjX0LEGC7cb4NoxqRJk=,tag:2+QnGVCFKs78+g/v9pjDzw==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-06-28T15:58:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAzk28srgkogfX+KOFYNA+7fgKje19RE19Ovzh/r72RQww
            /mSSE9CAZ76Ypja1sITl6lven57ueHxujTmVYDYToK5cBoA3NIxp4VGFL5671hy7
            0l4BdqMRNOV1yq2a1D0tNz5aq3XvnVIjQhKBU1/CFgJAsK0LCElILpT8lsu0ZrMI
            cMhZP9P75zrATTLGGYk8dE/bu3NYk7uX67H3FvJCQ+/6ktWfr1bBP4KTrsv6S/Gh
            =wIoR
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.1
