# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: shelfmark
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:3z0zlVIAaHVlqzeIqWjxXnmqRomEPel4y+zDgwd1/eige7C1OegTnwCvFPbY+goOXZYw7Vu+H46bBhmJIILgbRr5AVQoINQ2,iv:SI3DGCCOh/3tB2Hep4sTJkWBnqO9uqNDNC44pmS/AEM=,tag:zUQmZ/60RXT+ZogoX6hPtw==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbGZPYUZKTm5yencxNFVy
            cTU3WElLZW1ncmpmWGZvR1pucGtXRUtMclY4Ck9ZQnRtRThPTjNYRlY4K0hkRmNV
            Zmtvdjk2ZExsMzFpTndtSDNZTGJJRXMKLS0tIG50bVJYbXM1cVJPbkhWZFREdVZ4
            citObElUbU84RVVTMXZ2R1R6Sy94c28KimQTgK9g2f3Qs9a8APt6KZUfhbXxDWs9
            Q2yI0tP4DxGae7xZWjlw1k5X0QaRLEIiH3vWVRHnjW0raZiWVbdRyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T08:55:11Z"
    mac: ENC[AES256_GCM,data:qh4CqIB5gJTFKxZxyTezj0QsOkdirYr8T5RyqNb9Mg6RnCMDiglNTEGJtbYx8KJOIhH9z0FWrOqa1n9TYekLTOvwwJjPigJ4E0CWXiLSLY6HuZBlTlDaoH4aZYEJ5TBHxvM4wH0MSYyQCiH8qmTK1woKwgr2vkiGbRt0mDorw7Y=,iv:3toNbJzkg5iGZGA9q+NTAqO8QAcN+16iO9CrnL6pT7o=,tag:zZnvCkIpM8Bw4ZK9U65pDw==,type:str]
    pgp:
        - created_at: "2026-04-04T08:54:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAUBdXWJTvSk/LQsVXFsn40ytosLPgGQsOG3EQQqMMEmEw
            Ozdi9pEBb8dICtK0iByJj/VOQCUH6vL1b55GkihoYuXtR4YzuZMQwVkjEo6W/USj
            0lEBjCX/FQUcH9bFF/0RcpVDx3ypDWRL/wTyLYGXW3apsB0ZQdQ5ildUhgFoR/+6
            vopgNBdf4goRgSdijvSUQvGYCkR+P+CzBUHglFfHD/TMh/8=
            =nHLu
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
