---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: zigbee2mqtt
    files:
      - stack_config.json=./resources/stack_config.json
generatorOptions:
  disableNameSuffixHash: true
