# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: memini
stringData:
    MEMINI_API_KEY: ENC[AES256_GCM,data:SE05IX910UlKKsT1iDGgvpoPwh5llKwYE7layMIb/NLDCifUwkhgYn4mkx90dCPF/VA3JfjPYz46FXTe6hBK6g==,iv:Pry4vx0s//bOeHKMFUfVrkN4w1KM7LnmOIxMhaTXb3M=,tag:jNSfcFUlgqi3u3mJ8QLvSw==,type:str]
    LITELLM_API_KEY: ENC[AES256_GCM,data:A4EF0ore7doKSXcnxfKF+ibnbx4rtJRdqpzHDRRxLc18vILcahlTeNBAFjZ63f6xJUcvHYE+onq1i2lgm6Mbf7md2A==,iv:LdxZMY3iNqF4gPpu/1ehZADeqHmfEpeh18N8uuN4Zy0=,tag:SBOGbowzLCiOni2p21/CVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZjBLSFRNYVdHLzBCSm12
            c0k2QzRGYUtuUmJVWksxUzlKWXk3NEMzUGhNClRCTzdmYkJUR2pmbkQySWpYVEtU
            VDlVeVVEMGJ5TWREN0YrTDQ3ZG9iUjAKLS0tIEZvLy9mb0JZVWFDVDR6Vzh5Vnlh
            NU1vVXROWW9SQ2NjeU9neUdyaEEzdzQKF9bn5M1OcB0lXSWHMQesxc9B9OASxMjh
            cIqAUroUGjvLOM+3ho8BQbQUmPrhk7qDvOs4X/DXwxDwJ0lStm4fsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T07:22:38Z"
    mac: ENC[AES256_GCM,data:3MX6/wWgTPBwjb88F5pxRhMDcrT4YkEEdJmWJ8uUgr1XitW7/LxLjZBISSIQdp4UTrPVSrRDtGZk7Y193TS1DTge23slAYzZs6P/Sh5YBRHpZbM9BnlBikG22e+XeEwWH5gN2fjbeHD4oh8nHbMqT3Uek/JAW6hEwXfSpzjDcJY=,iv:x8Hh+ZR6mmlWzleI+LTkxo0UcruJ/B3Oz7J/q2rPoBE=,tag:A/E+0BlOQe1FUFwFNgkW1Q==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-05T07:14:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAtOGnJJjKXxymxvyojL7aXQiBc9NhhKeIV4ccPtjpmQYw
            tkQBxYiNVn7FmJizQFxXV0AJ+bso29v47NUldq1tOXfsMJUOOhd7DkLsFA0a8Hfd
            0lwBVfdlMi36mdmukb2eLp/JvfiVQhfYd4TgtME5EaH7lWLqZd7jcBZf4fQfjN0W
            WRkQBGQ4bGpPm9GUkFm7+vnVcG/dbmj3K1ISo9HDEBtc9EE6uJQOJ6vuRMqxZg==
            =NxMn
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
