# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secondary
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:5KmK79E=,iv:ZmbCWjoSXE6Q8gscSBr1zcr4KLPHSzRlrAXdzFAzyoo=,tag:SxNPfX1wwQ37DjqMMXOjsQ==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:VdKFx209MREAJn4oIy5/SfqY3iMj/n1qba0Lifg=,iv:mPcIlV8xVdKXaWlz7VDMWstYZn40v2V/NxYtcOnT7ek=,tag:IW+HHOVLwQciMPgOtUg5aw==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:0J35R+jID4N42DYX4a3wI6rI/QcQX/FgaF0mMmn1AySjV6AGCWNPNVivPZkPJsrjtdmUkBkxQ94FIi3QIplEHw==,iv:QeQIBqZHvCD30Vou6chsiVUQdaTTlbdEJ/I33csXpig=,tag:u8vS8EuKTU1UD45PNX1+fQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU3R0OStLb1AzN3RsbUJ0
            NWd4SVVrVlhoUnMwT0l2NG5YMWN6QnlodlZBCnkwMEdQL3lPVkkwTUF1SnZlbXd2
            ZnFLck1uK0RqdEZsbHpTUFNMQjlQSVkKLS0tIDdjOTlnd1lLUmVzYlFIMU9OUit0
            RWduam9FRnFzeHRkbzJoWTdrRWNKWlkKeUthTKuF4l3/BZM3GdtBqHoXCxqSo4TQ
            /cx5uuh2koUp8r2wVWLXxuwYNfpFQwrSbRFrmiSaQ+isiLXs98byhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T08:55:47Z"
    mac: ENC[AES256_GCM,data:r1dsmx1esA+waEw3Q7ANrazM1Apagp7hndaVknYP7NnKoHMCQSqfQG6O7YhfiVOo4xot24N9wWvEv/Xi2xm46T5E8/S2Q2v/SGHPfINcHJ84z3QibmBPnRTDPhLiy3pyQ6Xeh9Yivo6r2JP2v6AzZ6ZurkVf1+ofvT/PzcJr62A=,iv:EGTMkZ9AtbB4R3seQAK0uuFXcfTpdSTDRdjzc8d6zaU=,tag:AtzpfDRH4Bfc8TttUFnasQ==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-10-10T08:54:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAEvJfnoJt7ITeYxLQZv2l4URM7yscfd2r3xl5wBO0pXQw
            OCaOuSx+AK2JtaQfDyM5FyXb5fAzigQ1naYtFlRE05s3QNz9TpWCydcnkrF5nzVT
            0l4Bg67LeRUc0mRwwzY4B9F5aFvB1tnRbtz5lXK/h+ZLdKAImrEXz6DtSyg1ziaN
            3Pj0UKnQS+qh0ep0jldFupotJcOMPS7RfEtyTyKpa538JMkTOoMV8H28XcoP5kNe
            =IYKo
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
