# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: deduparr
stringData:
    DEDUPARR_RADARR_MOVIES_API_KEY: ENC[AES256_GCM,data:Zp3X6TRj9NmUQ+WtXjFyumXr9vz1qYDg8Pb8AE6O1cg=,iv:krx8hvMjwwgOnL/z1erbl5/o7HtE2XxjEaMNyIsP7Xs=,tag:fCozi4YKhYg43rhffYqg/g==,type:str]
    DEDUPARR_SONARR_SERIES_API_KEY: ENC[AES256_GCM,data:X7pUjT9aRvnSmIQSHK0WgIORdqpPQ8Qc3Npe21QWhE0=,iv:jP92k5cun6Ws3h9bf/LVA9jgHpWJiGMqF81G5xr18VM=,tag:7pyiYduTTfufj0xNg4iJZA==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTVlTR3YvRVFod0x6MTFn
            R0RIT24zSEZZaGdkRUlXVi9EeHNHMEJTM1JVClFjc2d5TFVRN1ZNbFhNY3FqS2M3
            QkZiLytSQVVEdFIrbDZEaDJQSjFOSUkKLS0tIHVKdG5RMkorMWlLRmNzTHkya0x2
            RGM0V1BqWFBsZVRnWCtrL1U0bVZzb28K0jklzn8KJPDo2kXjorQL6eF/naM0X6FS
            XW0AOI50ncysJABZkpiJNj0zV2dtj2T6jcno7gazCOBhvDjW4MArDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T18:49:54Z"
    mac: ENC[AES256_GCM,data:oTpUj15C92WiCpSsc52xqzaXrQdwtXe4jY7emrzM3Q/UDxbfjCdeN1U7VHnmerXOt66905tK8yPt0eLRDVN2ZVytqn19NBYXUe0rvR/ELjjwVFRf8n1sBjSwd+Cjha+q93k9ic5X6Yc3Ve74DYdJ5/FGIRWQFBkSEGARw6outV4=,iv:E/VqlhIg/b6Va+WJF3mCTOjufv5y9cBlQm7LqHNOcjo=,tag:462gg5ZjQHmOQSeqRhwd9g==,type:str]
    pgp:
        - created_at: "2026-03-22T11:31:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdA41jN/N4aoUSX7qZPu1Mu9B3V48QCyMslCyKBWv2DmAkw
            udWNY9EDFNoJ0ItqGTKeo0STp4qC2uUIK4bHkA5YygvBcU7BmMjuK7u62J1UpRA4
            0lwB9Y1ak7giNIqpvlyeCHcOSt+VxAzsoluf0XoPmI2uLJkIBJdQHQH72+FVXkXX
            MCS45kayJC0OqOcLeEnhknyzYCvef+Hm6nQyS2LjrSeoHBfaFB+u+R53RGt4Ag==
            =cykO
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
