---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/media/radarr/app
  interval: 1h
  timeout: 5m
  retryInterval: 1m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  targetNamespace: media
  components:
    - ../../../../components/zeroscaler
    - ../../../../components/ext-auth
    - ../../../../components/persistence
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
    substitute:
      APP: radarr
      CAPACITY: 1Gi
  prune: true
  wait: false
