---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/common
resources:
  - ./litellm-operator/ks.yaml
  - ./llmkube/ks.yaml
  - ./litellm/ks.yaml
  - ./open-webui/ks.yaml
  - ./ha-mcp/ks.yaml
  - ./memini/ks.yaml
