---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miroir
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/miroir-system/miroir/app
  interval: 1h
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  targetNamespace: miroir-system
  prune: true
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: miroir-config
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/miroir-system/miroir/config
  interval: 1h
  dependsOn:
    - name: miroir
  targetNamespace: miroir-system
  prune: true
  wait: true
