---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: ha-mcp
spec:
  alias: ha_mcp
  workload:
    # renovate: datasource=docker depName=ghcr.io/homeassistant-ai/ha-mcp
    image: ghcr.io/homeassistant-ai/ha-mcp:8.4.1@sha256:7823b36587a6e62efed271b26f3f72380b49f47364e5385580584e7ab2c60722
    port: 8086
    command:
      - ha-mcp-web
    env:
      - name: TZ
        value: Europe/Paris
      - name: HOMEASSISTANT_URL
        value: https://hass.${DOMAIN}
      - name: HOMEASSISTANT_TOKEN
        valueFrom:
          secretKeyRef:
            name: ha-mcp
            key: HOMEASSISTANT_TOKEN
    volumes:
      - name: tmp
        emptyDir: {}
    volumeMounts:
      - name: tmp
        mountPath: /tmp
