# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: ha-mcp
stringData:
    HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:yup1nmKRrGGGh4XFlnTsA9JftkOFSyCGIdZ91or5mUXbLBZoCs/9hAPMvdg30afna5FwjO7xlRezKZBC1FnFBCtF310cjsWoJycBMZyOnpYnUKSXd7duIXvIb4WDfrzNUw3ibNDroTok3xkZR8l2m1BcC5y2tn0mjKeSPN4am9kNDNWJvtEtop7zJ+819iObAUch1D5pcmufeAowIo0oPyBp+E12Gw29A/tuQa7D34OWqqNZiGxY,iv:DOanUo3gIU5teRCyvYMj8F8tyjmSUDkbE3vaTu7vflA=,tag:D0wsKE9Inp2z/nzreiopNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVENzWlFicWVoZmY5OEdB
            dTNtSTk0UG5pc2kvQ04zMFRGY0VrYTloVTFjCmdJWko4WVM3alA1WVdZRGx6bi9i
            bXQyUHdkRTYzVU91NHBnbEwzK0Zjb1EKLS0tIG5zZ2JWRjc2UmptWlNGdVcreDRz
            OURBQ2ZyalRXckhIVUxPMjh0MnRVVFUKqbN1igklzFCqJSy3miDUEZZ50s/mIb5s
            rIGDLgMGAyrhmInaxpHVRh5uz7/RJ+pamh/cPofSqD5wWEz1h6F5rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T06:33:55Z"
    mac: ENC[AES256_GCM,data:nv8CrPziS7hTT0Rr1m19kS0HBsduV0dgH3AvxoA0IA8FfhPh/JiRK7AhzOCm9xvYzoMD52RNA3Ra48T10FS5MTjisCRMaBEC25dB9hw961WmXU41bNyl6v8HBbVMdAtuEw+U7wUwViViYcxyUj6y7pKKeL6jaGd35LtDTO04Hb8=,iv:iv1hVm5aUloas/7UmbQwHAUcOW8Fb7xEGyGuFWruWhU=,tag:jqRbcA9aeAUVGzp4aaUt/w==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-03T06:55:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAb6hOG3x1sH19Iw/QlltZ2ESUK0FMzjCg2FArbkqRtkMw
            qVIiM9ul5keM6NHugzzHWo+85vz5Zl/osi+I3bHc8t7w7w1j8LKT6oAfsJl+PAK3
            0l4BHT3SLZmrJ4K5z9S/RzheW6H0oGjmCJl+ZyjVuz/ZieDiu05M558En1JbRl/x
            +TTvBSfmK++xyIfaZkgQwGzD9KEJbH/QGMo0/9/x48TpWDAdy5aEJXXrvRTXBIZX
            =d471
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
