# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: kopiur-nas
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cRoKTdP1,iv:zEuk3EdWaesMPzvNRhYyuNkYyYVuFSJckWtN7AgKQeg=,tag:WdTjGNFvzFA6UR1GNXPEsw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZP4XxLrGVapsjAOf8ZPd0Ltbyxs=,iv:0vBtnKySSp3JwBscW3yOF4JQJWMFBE+0d1WDh/VMcHY=,tag:FL+MLix7r2QkwuxySYfLmg==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:nwEBDL2XwjhXaYhhkSYjJ9ft0C0=,iv:YzViEOIwt9t/75Rf+afg5qga12p9IxoSAIIrPc8BdxM=,tag:LIfehQXx5GacyxpDMGmcmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiY3ZWSDI3RytrWUJJVW5r
            eUJGVUZvVHNpWTBHTUVXOXl5MkpQaDZDbmhrCk45cGtQRWRJZ1ZKaDNEWGJ0UlRQ
            aXhVZ0U3UXFkT0lHc25ZdUd3TjVIdEkKLS0tIEJxNWVoUmJ6eGUyVWc5NVFVWkM5
            RXVGbk5hTWU1Q01waFNxZk9SdXlvbFkK+XDdzd7pOwpxqFZ3joF5Sf7YR0x95XrK
            LQeX4iK+xyHQ6/aIRviRiy0CnEOyy8t5Z2UKFSr2ySMDyAJ+VwFVHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T11:23:05Z"
    mac: ENC[AES256_GCM,data:FRMHl/uBSLErrxPgI65r/vglPFy1EFcInKUxzHz/SRxgq0b48Adejjufv0Y/wJqVTPQwOAzcWJPTCTC4oK/kgahrMNOFnuL7aZ+fi3z7nBXPMoq+xCnE37MgA5KXz6Pnj9fTNiVrGNYlNrLsOiYiJcVC14eI9mEwfPmSTJ5w0qw=,iv:qPh/Jzw8qWc6i/ufL0hm2+y9Iett4pLzOhzGHU4jduk=,tag:8viIYs7f6wl6fd9ZVGMMuQ==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-08T11:21:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAIDgUm2nNIdddCTpsx2KiuGQTI3eX9/8ugSgHiT355mUw
            cmJrYZzEUQeZck2RiiN4++efYQV2baV3dui9ZZZrChx2D4Ld3mOS0lo5slwA6bRF
            0lwB3YFwXbWUOV6rgWfmFxM7H6TkvqPfBILJPs4XIqgZybScODQsoKsH7Qmq3wI4
            G7yh1AXQ7FwWCqQbo+tOQkeYBy6fIUY19HwgGy1VTt5vedJtcm/Mq9IPXZhF1w==
            =SMWW
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
