---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: singularity
spec:
  endpoints:
    - fqdn:
        hostname: singularity.milkyway
        port: 5001
