# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: bazarr
stringData:
    BAZARR__API_KEY: ""
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZi8vV3JwUkRSM0IzMCtn
            ZE1pU2dwVnBBQlQ0ZmRVQmloMzYwendsWFdVCmcvVTkwZHZNcFpKMTUzdGZjV0pN
            YWQrTEsxdnZsTi9sY3o2U0szZkNqM2cKLS0tIDZuVFRheEV2WWFrMVd0cHUzWE9G
            V1crVzVVYTJOcjMzZWVLOFRZT0tDOVkKI9flxxmKNWVrCRLyQbjI3P2ToRBor0jx
            Pzg6CIoLYv1v9u0ml8oWwP+jvNnuKsRTPSOS6XqV5yvOAUg7M3VT/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T11:31:47Z"
    mac: ENC[AES256_GCM,data:a21O+UKTMfXm81mS+Da5+fiUHNrXwaerPRLJCl4bapJy9P1gaHtLPPRkTZSYYJsSVPQY4+zyA/o3NbtTWp4vKU9wUDPYNewJJa9BQYhNw0WoF43JnemE5ALENClCucqpLwHRNVMISqc0268iHBGWdy0zq4KzW+6CguMbAA72blc=,iv:99yxLOauIQIZiVKfnZfWTYQrvUzCEJVV6Qxx07yq9mc=,tag:GBZ5vH3M7BEiPM+QYm0jBQ==,type:str]
    pgp:
        - created_at: "2026-03-22T11:31:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdA6oNQdLbw+4sAdGHw9Mz0pAC4XqNTgqPTDFEDcznt62cw
            woq3Xqsrpxn8KMu6Nax5TwCO/rBUKFCxz5Za+vQK/1dmMLXGUIkMQe1PBn4AN6is
            0l4B1t8fWuzJ1gWQlPJR8AYev4dFZ6fHi3rPhL/1K5bMDpImAfTryCV+n5ThUYfN
            Sa/V40aplXS3qbaSKwl0gcRxe3zVF3FJJgXt1NDxNaqptWZ/maIS4jlUdj9Llveg
            =Y4Sk
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
