---
- name: Install docker and docker-compose python modules
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
  become: true

- name: Install minio
  community.docker.docker_compose:
    project_name: minio
    pull: true
    definition:
      version: "3.7"
      services:
        minio:
          image: quay.io/minio/minio:RELEASE.2025-02-18T16-25-55Z@sha256:1df91be8d6a6146001cd6be2569a12785a8ece583b511f56ebed08f1e65d3611
          container_name: minio
          restart: unless-stopped
          command: server --console-address ":9010" /data
          volumes:
            - /volume2/minio:/data
          ports:
            - "9000:9000"
            - "9010:9010"
          environment:
            MINIO_ROOT_USER: "{{ minio_root_user }}"
            MINIO_ROOT_PASSWORD: "{{ minio_root_password }}"
            MINIO_PROMETHEUS_AUTH_TYPE: public
  become: true
