---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: claude-haiku-4-5
spec:
  modelName: claude-haiku-4-5
  params:
    model: anthropic/claude-haiku-4-5
    apiKeyRef:
      name: litellm
      key: ANTHROPIC_API_KEY
  info:
    maxTokens: 200000
    maxInputTokens: 200000
    maxOutputTokens: 64000
    supportsFunctionCalling: true
    supportsPromptCaching: true
    supportsVision: true
