---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./claude-opus-5.yaml
  - ./claude-sonnet-5.yaml
  - ./claude-haiku-4-5.yaml
