---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/database/cloudnative-pg/app
  interval: 1h
  timeout: 5m
  retryInterval: 1m
  targetNamespace: database
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-barman-cloud
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/database/cloudnative-pg/barman-cloud
  interval: 1h
  timeout: 5m
  retryInterval: 1m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: cloudnative-pg
      namespace: database
  targetNamespace: database
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/database/cloudnative-pg/cluster
  interval: 1h
  timeout: 5m
  retryInterval: 1m
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: cloudnative-pg-barman-cloud
      namespace: database
    - name: miroir-config
      namespace: miroir-system
  targetNamespace: database
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  wait: false
