# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:fg00HEFwHk3EOm7fb04FPXB/hr4=,iv:3XqGDsgsmQ8iMGyR/A/XAq6/L+sdp3QKx76SB+ibn9g=,tag:+qNHu3xfCUcDwd0sJTjP5w==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:kCQempjbAqEXavc/6kj6nI6Yat/UpestiDyswA==,iv:Sv4sEboDSCtrIUOgwCLtMeZdtcO+umOZqewhG0/PKJ0=,tag:zljmW/6c8eLtVKZXD30KFQ==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eVRnS3RDUFR0Zkg2ODlL
            aE5jTmp2VE5EaGVlZGZDeW4ra2dXZjVpWG53CnViOC9RSFUwc0NmQ3ArS0pOVVM0
            L3BVQkhBNmtDSGhFNlZwd3dpV1FPeFEKLS0tIHQrRnB2aW52bUU4aXpoWUgwbVdl
            WlcwbXFCWTE0T3EveWgwUERQSmNab2cKkgicxuOmZjo8L4Hxulj2fTIjbt5zqGah
            bIBNjmoJNJ3S32M81sU85ke8YRHxUe2rXH6wSX7eEunmc1N5uzwWig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T07:24:04Z"
    mac: ENC[AES256_GCM,data:jnz5LX3TuMc45Rp2lKSSVANQU9+bh16VjLt2LE57uFAF4NJZmwd2TaWxyC2wUmcmC/zmklZMh5kvGCpmWScPsLQLc6LpNc6RcrYybmPPfJ6OHFKBzq/KG0U0kXZBSWAgVfTUV7ZJy4mrfWUSWNJ4qMH/t+BiB4qhAoXdI/o0S1k=,iv:2magbpvsl4B+v+EtJzDPQ70TxWSmGIGcz+4p992i6Ek=,tag:17+bkvtmHKjpO36FC2wrVQ==,type:str]
    pgp:
        - created_at: "2025-09-21T21:37:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAvFsyFBPC1wOfyKDA98Pj0nMLSICQJvDZm18TJlPDCWcw
            b/hWMxhj8dM6qwOvddoDqP6EGxa9mDW1yEY1gLuVGOXd1rO/PUAfn9XTO2LzpZmx
            0lwBZETCHezBblbnkIWgCyTJsXE4CTjSIH11WRxFSavGR7yPZU9O4J1fBJVg7m75
            HhOiwQfIoyUwNDOyZ125bpql3yrOMHS6mMSEBO4oTX7mAzx1cDB4ssnEVtyy/A==
            =Atyg
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
