---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authelia.yaml
  - ./authelia.sops.yaml
  - ./autobrr.yaml
  - ./autobrr.sops.yaml
  - ./litellm.yaml
  - ./litellm.sops.yaml
  - ./lldap.yaml
  - ./lldap.sops.yaml
  - ./miniflux.yaml
  - ./miniflux.sops.yaml
