---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: lldap
spec:
  cluster:
    name: postgres18
  name: lldap
  login: true
  passwordSecret:
    name: lldap-db
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lldap
spec:
  cluster:
    name: postgres18
  name: lldap
  owner: lldap
