---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-csi-drivers
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/rook-ceph/ceph-csi-drivers/app
  interval: 1h
  timeout: 5m
  retryInterval: 2m
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  targetNamespace: rook-ceph
  prune: true
  wait: true
