---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frigate
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/home-automation/frigate/app
  interval: 1h
  timeout: 5m
  retryInterval: 1m
  dependsOn:
    - name: mosquitto
      namespace: database
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: node-feature-discovery-rules
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kopiur-repository
      namespace: kopiur-system
  targetNamespace: home-automation
  components:
    - ../../../../components/zeroscaler
    - ../../../../components/persistence
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
    substitute:
      APP: frigate
      CAPACITY: 5Gi
  prune: true
  wait: false
