# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: mam
stringData:
    MAM_SESSION_ID: ENC[AES256_GCM,data:BpTMvG8nVqSy5sXaKWBWp30Kqp+5jQu3aK72kep/nH2YFMfKV9LQKIJy50h/C4G2fF5yPGTNe6bxZJo/jH1rE7Sp4pAk5wynu3cOKyds91+Kt6rBaK1g9vw32v612ebsHe5b3WG+jwv+20i9/i7iMfDQYPNRdFPHaUNGD+kNcs6NmmSlaO0NcoZmBv/xfccGzYKQkB4oHf9h2kt1pRXegapOKmqQw6v2Fp0pjWGrwOWneynOmaHMabTaqF+bzH0QTcylj8Yq4yYAZKUyeIc8Gctkl5gvY6DBdZlhC7tcb8avfpSsLq3nB0PP2AAZeTjb1tfTJJKhaomUdAaL4B4LGr8QKIAHb9wlT5yKbxO4LROiYche5H3MG5DN/fR2oMb/Nn+Eqw==,iv:sc6tzGfnhTbMQcVw7ZnW5PLO1yFPOSa+9miKnOBXwzQ=,tag:HbmnP1xIUs0tQERgQU1x8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z2J2MHZSUkxWWHdYb0pQ
            cUc2dmhtMlFxK3kvUW1WQVYvRFNoOVZ0M2tZCnFSUTN1RFdDRWxQNGFSNytibUdJ
            TVB5R292STVSd2M0THNUa2VaTTZqUEEKLS0tIG9LZzcxQXZ3cUNTTTBGckVENXJh
            UnpONS9JVGFLK0krZmIyNnVVNHNWT2MKOGwor7MlucL4/1cuEn/IEO/izdEOujCM
            NxuoI6kHhgsml2K3hnENnr1DqBxxEv/ihCHoazcRthiliPY1naFndw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T19:56:13Z"
    mac: ENC[AES256_GCM,data:aZO3YLqjHrLLaXJc267S9A0qcX9/8huU2q1g9Lgz4yo2D1vj5nML25lkOtonOfVldo4ieCZL6jYmZN75SL2TVQkAGd8PiC0H3gWDZ/3tgydWBPbQ2g6b5ITl1bvCXON83Y4CMVX7tLhp51vK4PMIYGjzODbvSYMnsJ9to72Ry8E=,iv:ckWyh4h5B+9vUCU8J6wQIRYii3MI1OxSsRocpFvxGyw=,tag:cZrbdgmXsKNZ8q8+iur4HQ==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-04-04T07:58:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAL1tZiBwBKRAaxS8kMZJtNlJGIAXl8gBndhau/JtNvRow
            ILuc/RCf74cojYeNN6FWPxQvTKxVSK5yzfZ+m7dI0vw8/AQ4JM8YE8cUEuQBESfu
            0l4B6KZTUdov2AOYbjOVh3Ueq0RtALYTlm6piAa0eVaDfFp8EJk3YN36zF3T+MBo
            Ovz2eAPI6qzvmW/GPqDhuHGJ+9UZxWPPcVKZXStazmtKv/xdItQJRp88U8Hes/L5
            =TXT6
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.0
