# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: mam
stringData:
    MAM_SESSION_ID: ENC[AES256_GCM,data:hh1sfi7TlxSaVrNnLe28VhZBLqT6s9J6l0+MemZ46FWAwBR5Ba+QxfNFVjIo3v1/+/m2+P/J2GpFeKTD8MU2pj6sUpeLgyvSG8OUt+5vR0fTDvbbKSE9CF2QvgGNsVFkfHsjDlngsZMIieEh8q6GoQDR2rEQQpBDxYZ/lQCD0cOOhDc+sls9uOucFRT1MBK9t+uF/69KT2/MkCXU1S4vD1iopqhUuYjslTljBnxetcz29PBqZqS/GP/VLKplCu+z2JX1JUEnhr/tmvMi6NIKvCbEc12iMZ0mo743655O3Pga86MFwEzLuwxA+HMKX7+3oMxGpHrM8+RCUYCgTBddHgff5JlutycCGBZu4QsQ1PzHlLk/AAGQNeTF1kFD8LVjDGWCKg==,iv:dC+gkPkxPZOBJl1MKlZNYgr0E4ZYb09qMj5Pn2FCIAM=,tag:jdw3+EgHGOtoG2qdMGBR/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z2J2MHZSUkxWWHdYb0pQ
            cUc2dmhtMlFxK3kvUW1WQVYvRFNoOVZ0M2tZCnFSUTN1RFdDRWxQNGFSNytibUdJ
            TVB5R292STVSd2M0THNUa2VaTTZqUEEKLS0tIG9LZzcxQXZ3cUNTTTBGckVENXJh
            UnpONS9JVGFLK0krZmIyNnVVNHNWT2MKOGwor7MlucL4/1cuEn/IEO/izdEOujCM
            NxuoI6kHhgsml2K3hnENnr1DqBxxEv/ihCHoazcRthiliPY1naFndw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T12:17:36Z"
    mac: ENC[AES256_GCM,data:e0xriOW/8tDI0gkGKIoHkmCBAhSrVEefYel9T9YfnRb7j/B7AjpYl1AAPs35Nf17TsIEYroIfBrhTsK+G4HtiZboNDT0IMHfW5HGapgOqCbEwCy2hvIbN/akdXHpKrOZ4Eiczjo7rOFGxVaW287m5nQG+X5741PGBOpcbOqWP6A=,iv:RsIOe0r9FQP/kjeDvzOAjyXXs22uy7zyiB2sCv74eVI=,tag:lOBk91cwwuFP/3NE35ScVw==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-04-04T07:58:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAL1tZiBwBKRAaxS8kMZJtNlJGIAXl8gBndhau/JtNvRow
            ILuc/RCf74cojYeNN6FWPxQvTKxVSK5yzfZ+m7dI0vw8/AQ4JM8YE8cUEuQBESfu
            0l4B6KZTUdov2AOYbjOVh3Ueq0RtALYTlm6piAa0eVaDfFp8EJk3YN36zF3T+MBo
            Ovz2eAPI6qzvmW/GPqDhuHGJ+9UZxWPPcVKZXStazmtKv/xdItQJRp88U8Hes/L5
            =TXT6
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.1
