---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: mam
stringData:
  MAM_SESSION_ID: ENC[AES256_GCM,data:JmS2wPH7vt9NSti6YicSyPdn/QX9g+TnoxfRUTIXsl3T2mrtyQnA9H3qb6+jcAL6nEyX0QPMpoakP5eZ6veAcsymMfzmFdkIPkLpvtuSMQLZTwT1nLb6P6xiaReKN88PJhp1zhftk5Q/CwcDsOn/mVTseOUswwU6LxKz93ynGcVN/HEtJ/mU8euSS+3mXABU8QBveg9OXXZvF5rLfBDTKHhH2WtZ3zK57zsx5y+wCKX5xNeG+YAY7efMI4CeQE7D6xZbMo0FXVOcbn2KiIx2O88lHUkCRIDB3UmObo5b2DsUboV6480Vi2AXT6bdKXB06QM9avJ9kJPTtb7scHDJtbzAsEr6+ps0T+8j5iK3eQNnt1xWWBuR2gWboIAUYy2EndprsQ==,iv:oGyApwXS+DMREktAijl2/jukm1670rk1v8LoOiXOefY=,tag:AdsglggkIwqIFFQD4yKUaA==,type:str]
sops:
  age:
    - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z2J2MHZSUkxWWHdYb0pQ
        cUc2dmhtMlFxK3kvUW1WQVYvRFNoOVZ0M2tZCnFSUTN1RFdDRWxQNGFSNytibUdJ
        TVB5R292STVSd2M0THNUa2VaTTZqUEEKLS0tIG9LZzcxQXZ3cUNTTTBGckVENXJh
        UnpONS9JVGFLK0krZmIyNnVVNHNWT2MKOGwor7MlucL4/1cuEn/IEO/izdEOujCM
        NxuoI6kHhgsml2K3hnENnr1DqBxxEv/ihCHoazcRthiliPY1naFndw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T08:21:06Z"
  mac: ENC[AES256_GCM,data:PrsUN+bePJOTajjN3nsM7SMByc+usFYjxGlzb2GYgBI5XVar2d4NQHPqWwITVpxuOjJVkxKKcCIYxsEVN6DW4wSuWl8vs2kHjqZw591/UiosOehkgvpVJpuLXpdFJqnVa/O4fwwwq9ZYceDDzRlQCfNjwvoJJo7FyxgpCH8URZ4=,iv:chUH8ppaLTsHjAQKftvKfY7TDgLA4A/puny18UCTaGE=,tag:rn5UznEpV3cdLbbGdvC0vQ==,type:str]
  pgp:
    - created_at: "2026-04-04T07:58:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DopS/VjtMxJoSAQdAL1tZiBwBKRAaxS8kMZJtNlJGIAXl8gBndhau/JtNvRow
        ILuc/RCf74cojYeNN6FWPxQvTKxVSK5yzfZ+m7dI0vw8/AQ4JM8YE8cUEuQBESfu
        0l4B6KZTUdov2AOYbjOVh3Ueq0RtALYTlm6piAa0eVaDfFp8EJk3YN36zF3T+MBo
        Ovz2eAPI6qzvmW/GPqDhuHGJ+9UZxWPPcVKZXStazmtKv/xdItQJRp88U8Hes/L5
        =TXT6
        -----END PGP MESSAGE-----
      fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
