# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: romm
stringData:
    DB_PASSWD: ENC[AES256_GCM,data:Ok1M67f6v2X9O+OL/ozyH/i8k7BgxwjpPMmpY94VTO4=,iv:RmkkIdPbsPcnZW11MfM/rV4omG5Nnk37CgmnZ2kr8HE=,tag:FRYCsV3Qr3YVg/Tdj0T9nA==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:C+to4OontBG0jzUyJ05p+FTwClAlIHvFfNN2bYpmOg2hdKjui3v5XdVKb6LS/U0tfFsEeIVQGJpPqg8aizHTZw==,iv:jS6tChdSH1JCVu1rt8Y1n14MKKXtFC+OcMknm10ySNU=,tag:+pfXqmqPbmCPJP0aLvEEUQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Jy4vTzRH0qyCrjdKbVSPeeck/jTRyE7JO8Y4qhkW0cLRa0ZcKqUv7y2/LHzLZZYS4VarztKcPTZljhqhGVV73q1l2yhCelYh,iv:1BxtLHdQdOAdE3yk9/k/jrrP8Bt0bhey2+j+ONHz+04=,tag:Nf5kMBkG2V/EWqzzbzKSbg==,type:str]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:g4talT4jV/crQAjJuUrSpkJTx0aQJIw1V4CdaS4u,iv:NqcdDVfiHuV3GIJw3G6ooGaoBXfVJrBlvotTjOBwnDU=,tag:XU6LAYLGUwjQPLlsNTirrQ==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:Xjq2MtX8QUCyhT/QJRaIPKpQuvhl2Rsqm2aJNVu5,iv:pQjUxeXv7DSESZt9g1TKgtzm4tJiIKd5GRCBNpk3rYs=,tag:MLmT06WjQQH0voWRjHdXtQ==,type:str]
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:ZgpWD6Nqb3Wm4z3L4y5yQ+LO66878XGhTwTSzM/PMj8=,iv:FLss1S4rVNkibA8itJ7oBi/4Y6UvLhW94SPkpVmOJ7g=,tag:IOZEwBGHsjQ9mltBgFKbkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTklHMXBwWi9sbFZEQVZ3
            NmE0Qm41Mzc0VjZkT2FkdC9PVVNLNi9tQ0ZFClU0by8vY0VIcFFETWoyV0dwM2l4
            OFpWSWZvNitRNkRROTkwclNYNHJkS2MKLS0tIGM4TXo0Sk01NkRvL3VrOHVEQkJ5
            NG80bVA0WjFIdlZPanp6YTJwMmZCVzgKui7G0EysfwKGXs/eutFacCqGKWD94jSE
            UOHExCFZahTF7TuE4MOVopxQAmyfDsG3rhO8sX8AIl1xF/yMG9pfXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T19:42:18Z"
    mac: ENC[AES256_GCM,data:E4Ey9a/pR3WF17qzVjBylAMuZz+hOkt8eWoU14y4u0tmQHhnFo/EPkz46Z4E7EL1riXm2ld9Y+kfX6NcrTN8lwyeDPrjka/mFJWAwaqdhbywdhO/HQtqEQ8VOKCup7UyyoZgePUhdtL2wNLnFAYO2cb5w0Sxa8TSoppRNqWWnqg=,iv:m0pL7cJKAm8RE5aeenIsvaynJNrgMinvW+CKvLAl8dA=,tag:/lygaV2gfE5vBxIFyEeYBA==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-09-24T19:42:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdACPRXKKDOayWIwl6CgUrlmZ7XygxSFzgs3I5uaBHbd20w
            98ZN+6XC0wcRJKLacWNVAVlR3YZKtF1tC2aB1lUKqSYfVFb2XAL/xdteG76zXRH5
            0l4B63IqNaEu7IFJ1r+r344sqBrv3rGQKFx4UWP7dQ/IohTtEwxhFxWCw8OKKiul
            cNsVGyC37Xlx4ZvcSdLD2X/tDjMSd/3Ri2XWvnHgVkvfd9HBg8DCqbXffIBYFtrJ
            =8ps/
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
