# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: open-webui
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:Z4l8RWSrVTAlCVR7M3e1eUDuSbB90x3S1KNj3CosphF7MI+tUi7sqrqz3mw=,iv:grcYx3yOIaQOpOya+swl5G8d7TbKboqfvDxzGvWvglw=,tag:Pi9wId1NTL8eh70YmXAcXg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:yt0v4FQYf2V5DGZYhw4Ja9xUlXmznjf0XUS7hofRVORfGlrwCa6H0HjcLUTF+VPaq/Eg3vUvzsL80jwl/f2jwvVvyw==,iv:VuhlRXp+H4OHgdBQ7+cna4NxCBleXI/10ulyE5n1p0w=,tag:lVjkPUUCHWgkbSkmD8b/AA==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:1DEJCmtzCX9uOw==,iv:+R5ZrglMXGQuqMtpGXfbAXVaXUDaCojpQqWrmaQThsM=,tag:fZ4MpPjc3vXfhoKQ5NH+eQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:DlC/NjP1vR50ZztJFp+pe8wlIMs4WejptLUf5JFdPxoEvrjBwQGgTSkPE79TRAdknLtujzXku7veMYxqjLahuWIQ0C2zc6zb,iv:jwiqXFYXULw0g2T6R8GEw14sdkx3yoCHFK8DW57uv2Y=,tag:LpSN2fxEXzEgIrkUiBnC+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WmhHeThPeTE3Y3RqSUk1
            Q3hFT1czQ0xqTml4MXhzQ1JUd3hEVEpYMlNVCkIwL2dxd3A1VFZnS1BKbWVtUTFa
            bTVCSmlaS1dQekJmS01DYWUvY3FMYVUKLS0tIHhTOG9RdVA1emdoTkFFNEFGSWtF
            Q3BPZHJHdE5aaThNc1BpVnNmTUtabDAKigS5oPgU4l8C2yHJIurqZaLGIB2V3ot6
            vWh1GSCsO65XYNzIGO9sCyK/CkxWMCUb+oicD0PCeZtzlkyWkiNPkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T06:30:46Z"
    mac: ENC[AES256_GCM,data:FPJ0p5rs/qM1/yHF4FT39C5vzYCBfIsxWMP+ye/VB+/X2AeTpGlZ+nsJhAzzTzFsegLV+rgdM3tkjndNrpRbtcrlSMn8/MVHE24TbzO4AAQalQgKmw0L0dD/FgL6zXXM4Y3D95v3k0TsQd952337xY8YW4QXwIBbPLlCjunIZY8=,iv:ph6ycA3eOLzqFvqQhKiGktwrO4TKIa637zxbCOMw4wc=,tag:/XFF8kH/PCcLvkwH2OV8GA==,type:str]
    mac_only_encrypted: true
    pgp:
        - created_at: "2026-08-03T06:55:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdA5OGCu6PAA56F0wYrgUMT2JCMunAsdz/vhQ9dNN3gnn0w
            guwbW9WUNcVwM59UMH3/PIsIF240PPGRH3M1NFPO/xDZuwNnfSJbpQRwp3VFFkdr
            0l4Bj6MjAaKA5fkLTAwLs95M+HexuI74jk4aSZxEWtHY+AQ98KB9cK5yfLF0j6Cp
            4b4FyEtKCA3oO9N0gHNzrbA8o2FMbPDzUr3Asl8X45zZ+EbRJ1h7EwIyObm9GhBY
            =pJe8
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    version: 3.13.3
