---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/security/authelia/app
  interval: 1h
  timeout: 5m
  retryInterval: 1m
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: dragonfly-operator
      namespace: database
    - name: lldap
      namespace: security
  targetNamespace: security
  components:
    - ../../../../components/dragonfly
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
    substitute:
      APP: authelia
      DRAGONFLY_REPLICAS: "3"
  prune: true
  wait: false
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      current: status.phase == 'ready'
      failed: status.phase != 'ready'
